# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Fisica per le superiori
author: basics
logo: logo.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off # force # auto # cache

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: xelatex
  uset_jupyterbook_latex: true
  latex_documents:
    targetname: book.tex
# latex_additional_preamble: |
#   % Custom dropdown style
#   \usepackage{tcolorbox}
#   \usepackage{amsthm}
#   \tcbuselibrary{listingsutf8}
#   \tcbuselibrary{theorems}

#   % Define a colored box for admonitions
#   \newtcolorbox{customdropdown}[1][]{
#     colback=blue!10,
#     colframe=blue!50!black,
#     fonttitle=\bfseries,
#     title=#1,
#     sharp corners,
#     boxrule=0.5mm,
#     left=3mm,
#     right=3mm,
#     top=1mm,
#     bottom=1mm
#   }
#   
#   % Define a new environment for definitions
#   \theoremstyle{definition}
#   \newtheorem{definition}{Definition}[section]

#   % Optional: Redefine the appearance for definitions using tcolorbox
#   \usepackage{tcolorbox}
#   \tcolorboxenvironment{definition}{
#     colback=green!5,
#     colframe=green!60!black,
#     fonttitle=\bfseries,
#     sharp corners,
#     boxrule=0.75mm,
#   }
    
    
#   % Custom definition style
#   \newtcolorbox{customdefinition}[1][]{
#     colback=green!5,
#     colframe=green!50!black,
#     fonttitle=\bfseries,
#     title=Definition,
#     sharp corners,
#     boxrule=0.75mm,
#     left=3mm,
#     right=3mm,
#     top=1mm,
#     bottom=1mm,
#     #1
#   }

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# search: # not working
#   enable: True

# Information about where the book exists on the web
repository:
  url: https://github.com/Basics2022/bbooks-physics-hs  # Online location of your book
  branch: master                                        # Which branch of the repository should be used when creating links (optional)
# path_to_book: docs                                    # Optional path to your book, relative to the repository root

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  analytics:
    google_analytics_id: G-R3GS2LVD8M
  home_page_in_navbar: True
  use_issues_button: true
  use_repository_button: true
  extra_navbar: ""
# extra_templates_path: ["_templates"]
# extra_footer: |
#   <script async src="https://www.googletagmanager.com/gtag/js?id=G-R3GS2LVD8M"></script>
#   <script>
#     window.dataLayer = window.dataLayer || [];
#     function gtag(){dataLayer.push(arguments);}
#     gtag('js', new Date());
#     gtag('config', 'G-R3GS2LVD8M');
#   </script>

# sphinx extensions
sphinx:
  config:
    language: it
    html_theme_options:
      logo:
        image_light: logo.svg
        image_dark: logo-dark.svg
      repository_url: https://github.com/Basics2022/bbooks-physics-hs  # Online location of your book
      repository_branch: master
      use_repository_button: True
      use_edit_page_button: True
      use_issues_button: True
      launch_buttons:
        colab_url: "https://colab.research.google.com"    # colab
    html_favicon: favicon-sugar.svg
    bibtex_bibfiles: [ "bibliography.bib" ]
  extra_extensions:
    - sphinx_proof
    - sphinx_exercise
    - sphinxcontrib.bibtex
    - sphinx.ext.autodoc  # keep existing extensions
    #  footer_include: "_templates/footer.html"
# extra_templates_path:
#   - _templates
    # - sphinx_togglebutton   # to be installed


